config/routes.rb
Rails.application.routes.draw do

  resources :games, only: [:new, :show, :create], param: :game_id do
    resource :attack, only: [:create]
    resources :quests, only: [:new, :show, :create, :update]
  end

  root to: "games#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/army.rb
class Army
  attr_reader :cards

  def initialize
    @cards = []
    get_army
  end

  def to_s
    cards.map(&:to_s)
  end

  private

  def get_army
    while cards.length < 5 do
      new_name = Faker::Movies::LordOfTheRings.character
      name_exists = !cards.detect { |c| c.warrior_name == new_name }.nil?
      cards << Warrior.new(warrior_name: new_name) unless name_exists
    end
  end
end

app/models/game.rb
class Game < ApplicationRecord
  serialize :game_state

  validates :game_id,     uniqueness: true, presence: true
  validates :game_state,  presence: true

  # Game State
  # {
  #   game_id: <string>,
  #   player_one: {
  #     name: <string>,
  #     army: <Army>
  #   },
  #   player_two: {
  #     name: <string>,
  #     army: <Army>
  #   },
  #   current_player: <string>,
  #   opposing_player: <string>,
  #   turn_result: <string>,
  #   available_quests: [<string>],
  #   current_quest: <string>
  # }

  def to_param
    game_id
  end

  def player_one
    game_state&.dig(:player_one, :name)
  end

  def player_two
    game_state&.dig(:player_two, :name)
  end

  def player_one_hand
    game_state&.dig(:player_one, :army)&.cards || []
  end

  def player_two_hand
    game_state&.dig(:player_two, :army)&.cards || []
  end

  def current_player
    game_state&.dig(game_state&.dig(:current_player).to_sym, :name)
  end

  def opposing_player
    game_state&.dig(game_state&.dig(:opposing_player).to_sym, :name)
  end

  def turn_result
    game_state&.dig(:turn_result)
  end

  def available_quests
    game_state&.dig(:available_quests)
  end

  def set_current_quest(quest_id:)
    game_state[:current_quest] = quest_id
    save!
  end

  def current_quest
    game_state&.dig(:current_quest)
  end
end

app/models/hero.rb
class Hero
end

app/models/monster.rb
class Monster
end

app/models/quest.rb
class Quest

  def self.all
    [
      {
        quest: "nemean_lion",
        name: "Hercules",
        labor: "Kill the Nemean Lion",
        type: "hero"
      },
      {
        quest: "stymphalian_birds",
        name: "Achilles",
        labor: "Kill the Stymphalian Birds",
        type: "hero"
      },
      {
        quest: "cretan_bull",
        name: "Perseus",
        labor: "Capture the Cretan Bull",
        type: "hero"
      },
      {
        quest: "erymanthian_boar",
        name: "Minotaur",
        labor: "Capture the Erymanthian Boar",
        type: "monster"
      },
      {
        quest: "lernean_hydra",
        name: "Medusa",
        labor: "Kill the Lernean Hydra",
        type: "monster"
      },
      {
        quest: "cattle_of_geryon",
        name: "Kraken",
        labor: "Capture the Cattle of Geryon",
        type: "monster"
      },
    ]
  end
end

app/models/warrior.rb
class Warrior
  attr_accessor :attack, :defense, :warrior_name

  FULL_ATTACK   = 5
  FULL_DEFENSE  = 3

  def initialize(warrior_name:)
    self.attack       = FULL_ATTACK
    self.defense      = FULL_DEFENSE
    self.warrior_name = warrior_name
  end

  def to_s
    "Name: #{warrior_name}, Attack: #{attack}, Defense: #{defense}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attacks_controller.rb
class AttacksController < ApplicationController
  def create
    AttackService.attack(**attack_params)
    redirect_to game_path(params[:game_game_id])
  end

  private

  def attack_params
    params
      .require(:attack)
      .permit(:attacker, :defender)
      .to_h
      .symbolize_keys
      .merge({ game_id: params[:game_game_id] })
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :load_game, only: :show

  def new
    @game = Game.new
  end

  def show
  end

  def create
    game = GameService.create_game(**game_params)
    redirect_to game_path(game)
  end

  private

  def game_params
    params
      .require(:game)
      .permit(:game_id, :player_one, :player_two)
      .to_h
      .symbolize_keys
  end

  def load_game
    @game ||= Game.find_by(game_id: params[:game_id])
  end
end

app/controllers/quests_controller.rb
class QuestsController < ApplicationController
  before_action :load_game

  def new
  end

  def show
    @quest = Quest.all.detect { |q| q[:quest] == params[:id] }
  end

  def create
    game.set_current_quest(quest_id: quest_id)
    redirect_to game_quest_path(game, quest_id)
  end

  def update
  end

  private

  attr_reader :game

  def quest_id
    @quest_id ||= params.require(:quest).permit(:quest_id)[:quest_id]
  end

  def load_game
    @game ||= Game.find_by(game_id: params[:game_game_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_card.html.erb
<div class="col-2">
  <div class="card <%= player %>">
    <%= image_tag "greek-warrior-#{image_index}.jpg", alt: card.warrior_name, class: "card-img-top" %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div title="<%= card.warrior_name %>" class="warrior-name">
          <%= card.warrior_name %>
        </div>
      </li>
      <li class="list-group-item">
        <%= "Attack: #{card.attack} / #{Warrior::FULL_ATTACK}" %>
      </li>
      <li class="list-group-item">
        <%= "Defense: #{card.defense} / #{Warrior::FULL_DEFENSE}" %>
      </li>
    </ul>
  </div>
</div>

app/views/games/new.html.erb
<div class="row">
  <div class="col-5 offset-6">
    <%= form_with model: @game, remote: false do |f| %>
      <div class="form-group">
        <%= label_tag(:game_id, "Game Identifier:") %>
        <%= f.text_field :game_id, class: "form-control", "aria-describedby" => "gameIdHelp", placeholder: "sea-of-monsters" %>
        <small id="gameIdHelp" class="form-text text-muted">
          This will be used as the website url for your game. Please only use lower <br/>
          case letters and numbers, and no special characters other than "-" or "_".
        </small>
      </div>
      <div class="form-group">
        <%= label_tag(:player_one, "Name of Player One:") %>
        <%= f.text_field :player_one, class: "form-control", placeholder: "Zoe Nightshade" %>
      </div>
      <div class="form-group">
        <%= label_tag(:player_two, "Name of Player Two:") %>
        <%= f.text_field :player_two, class: "form-control", placeholder: "Nico di Angelo" %>
      </div>
      <%= f.submit "Let's Battle!", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<div class="row">
  <div class="col">
    <div class="player">
      <h4><%= @game.player_one %></h4>
    </div>
  </div>
  <% @game.player_one_hand.each_with_index do |card, i| %>
    <%= render partial: "card", locals: { card: card, i: i, image_index: "1", player: @game.game_state[:current_player] == "player_one" ? "attacker-card" : "defender-card" } %>
  <% end %>
</div>
<div class="row">
  <div class="col-2">
    <div class="player">
      <h4><%= @game.player_two %></h4>
    </div>
  </div>
  <% @game.player_two_hand.each_with_index do |card, i| %>
    <%= render partial: "card", locals: { card: card, i: i, image_index: "4", player: @game.game_state[:current_player] == "player_two" ? "attacker-card" : "defender-card" } %>
  <% end %>
</div>

<% content_for :turn_status do %>
<div class="row">
  <div class="turn-status col-8 offset-4">
    <% if @game.turn_result %>
      <p>
        <%= @game.turn_result.html_safe %>
      </p>
    <% end %>
    <h4>
      <%= @game.current_player %>, it's your turn.
    </h4>
    <p>
      Select your warriors and...
    </p>

    <%= form_with(url: "/games/#{@game.game_id}/attack", method: "post", id: "attackForm") do %>
      <%= hidden_field :attack, :attacker, id: "attackerField" %>
      <%= hidden_field :attack, :defender, id: "defenderField" %>
      <%= button_tag "Fight!", type: "button", class: "btn btn-success", data: { toggle: "modal", target: "#confirmFightModal" } %>
      or
      <%= link_to "Quest!", new_game_quest_path(@game), class: "btn btn-info" %>
    <% end %>
  </div>
</div>
<% end %>

<div class="modal fade" id="confirmFightModal" tabindex="-1" role="dialog" aria-labelledby="confirmFightModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmFightModalLabel">Shall we proceed?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body confirmation-message">
        You must select an attacker and defender to continue.
      </div>
      <div class="modal-footer">
        <%= audio_tag("swordraw.mp3") %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button id="confirmAttack" type="button" class="btn btn-success" data-dismiss="modal">Attack!</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Battles of Olympus</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag("favicon") %>

    <%= stylesheet_pack_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </head>

  <body>
    <div class="dimmer"></div>
    <div class="container">
      <div class="row">
        <div class="col-6">
          <%= yield :turn_status %>
        </div>
        <div class="col-6">
          <h1>Battles of Olympus</h1>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/quests/_card.html.erb
<div class="col-4">
  <div class="card quest-card" data-quest-id="<%= quest[:quest] %>">
    <%= image_tag "#{quest[:name]}.jpg", alt: "#{quest[:name]}: #{quest[:labor]}", class: "card-img-top" %>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <div title="<%= "#{quest[:name]}: #{quest[:labor]}" %>" class="name">
          <%= quest[:name] %> (<%= quest[:type].titleize %>)
        </div>
      </li>
      <li class="list-group-item labor">
        <%= quest[:labor] %>
      </li>
    </ul>
  </div>
</div>

app/views/quests/new.html.erb
  <% @game.available_quests.each_with_index do |quest, i| %>
    <% if i % 3 == 0 %>
      <div class="row">
    <% end %>
    <%= render partial: "card", locals: { quest: quest, i: i, offset: 0, player: "" } %>
    <% if i % 3 == 2 %>
      </div>
    <% end %>
  <% end %>
</div>

<% content_for :turn_status do %>
<div class="row">
  <div class="turn-status col-8 offset-4">
    <h4>Please select your quest.</h4>
    <%= form_with(url: "/games/#{@game.game_id}/quest", method: "post", id: "questForm") do %>
      <%= hidden_field :quest, :labor, id: "questField" %>
      <%= button_tag "Begin Quest", type: "button", class: "btn btn-success" %>
    <% end %>
  </div>
</div>
<% end %>

<div class="modal fade" id="confirmFightModal" tabindex="-1" role="dialog" aria-labelledby="confirmFightModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmFightModalLabel">Shall we proceed?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body confirmation-message">
        You must select an attacker and defender to continue.
      </div>
      <div class="modal-footer">
        <%= audio_tag("swordraw.mp3") %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button id="confirmAttack" type="button" class="btn btn-success" data-dismiss="modal">Attack!</button>
      </div>
    </div>
  </div>
</div>

app/views/quests/show.html.erb
<div>
  <div class="row">
    <div class="col-4 offset-4">
      <div class="card quest-card" data-quest-id="<%= @quest[:quest] %>">
        <%= image_tag "#{@quest[:name]}.jpg", alt: "#{@quest[:name]}: #{@quest[:labor]}", class: "card-img-top" %>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
          </li>
          <li class="list-group-item">
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

<% content_for :turn_status do %>
<div class="row">
  <div class="turn-status col-8 offset-4">
    <h4><%= @quest[:labor] %></h4>
    <%= form_with(url: "/games/#{@game.game_id}/quest", method: "post", id: "questForm") do %>
      <%= button_tag "Do Quest Stuff", type: "button", class: "btn btn-success", data: { toggle: "modal", target: "#startQuestModal" } %>
    <% end %>
  </div>
</div>
<% end %>

<div class="modal fade" id="startQuestModal" tabindex="-1" role="dialog" aria-labelledby="startQuestLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="startQuestLabel">Shall we proceed?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body confirmation-message">
        You must select a quest to continue.
      </div>
      <div class="modal-footer">
        <%= audio_tag("swordraw.mp3") %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button id="confirmQuest" type="button" class="btn btn-success" data-dismiss="modal">Let's Go!</button>
      </div>
    </div>
  </div>
</div>